application:
  name: string # Name of the application
  description: string # Description of the application
  version: string # Version of the application
  author: string # Author of the application
  createdAt: string # Date of creation of the application
  updatedAt: string # Date of last update of the application

modules:
  - name: string # Name of the module
    description: string # Description of the module
    resources:
      - moduleEndpoint: string # Module endpoint
        description: string # Description of the module endpoint
        endpoints:
          - path: string # URL path of the endpoint
            description: string # Description of the endpoint
            methods: [string] # Array of HTTP methods (e.g., GET, POST, PUT, DELETE)
            action: string # Action associated with the endpoint
            function: string # Name of the function associated with the endpoint
            checks: # Object representing checks for the endpoint
              [key: string]: any
            input_schema: string # Input schema for the endpoint
            output_schema: string # Output schema for the endpoint
            auth_required: boolean # Indicates if authentication is required for the endpoint
            middleware: string # Name of the middleware applied to the endpoint
            integrations: [string] # List of integrations used by the endpoint
            service: string # Name of the service associated with the endpoint
            return: # Return structure for the endpoint
              [statusCode: string]:
                description: string
                data:
                  prisma:
                    model: string
                    action: string
                    args:
                      select:
                        - [key: string]: string
                      include:
                        - [key: string]: string
                      skip?: number
                      take?: number
                      orderBy?:
                        [key: string]: string
                      where?:
                        - [key: string]: string
